[eventlistener:dependency_listener]
command         = python3 /opt/hermes/supervisord/scripts/dependency_listener.py
autostart       = true
autorestart     = unexpected
startretries    = 0
exitcodes       = 0
buffer_size     = 10
events          = PROCESS_STATE_RUNNING,PROCESS_STATE_STOPPED,PROCESS_STATE_FATAL,PROCESS_STATE_EXITED
priority        = 1
stdout_logfile  = /var/log/supervisor/dependency_listener.stdout.log
stderr_logfile  = /var/log/supervisor/dependency_listener.stderr.log
stdout_logfile_maxbytes = 5MB
stderr_logfile_maxbytes = 5MB
