[program:pyload]
command         = docker compose -f /opt/hermes/stacks/vpn/docker-compose.yml --env-file /opt/hermes/.env.ports --env-file /opt/hermes/stacks/vpn/.env up --no-log-prefix --no-color pyload
directory       = /opt/hermes/stacks/vpn
priority        = 20
autostart       = false
autorestart     = false
startretries    = 0
startsecs       = 5
stopwaitsecs    = 10
stdout_logfile  = /var/log/supervisor/pyload.stdout.log
stderr_logfile  = /var/log/supervisor/pyload.stderr.log
stdout_logfile_maxbytes = 10MB
stderr_logfile_maxbytes = 10MB
stdout_logfile_backups  = 3
stderr_logfile_backups  = 3
