services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${GLUETUN_HTTP_PROXY_PORT}:8888/tcp
      - ${GLUETUN_SHADOWSOCKS_PORT}:8388/tcp
      - ${GLUETUN_SHADOWSOCKS_PORT}:8388/udp
      - ${PYLOAD_PORT}:${PYLOAD_PORT}/tcp
    volumes:
      - gluetun_data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - TZ=${TZ}
    restart: "no"       # supervisord handles restart policy

  pyload:
    image: linuxserver/pyload-ng:latest
    container_name: pyload
    network_mode: "service:gluetun"   # routes through gluetun
    volumes:
      - pyload_data:/config
      - pyload_downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEB_PORT=${PYLOAD_PORT}
    restart: "no"       # supervisord handles restart policy

volumes:
  gluetun_data:
  pyload_data:
  pyload_downloads:
